'''Build a conversational AI that can decide when to use tools (like a Web Search tool or a Calculator) to answer a user's question, and when to respond directly.'''

import operator
from typing import Annotated, TypedDict, Literal
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

# ==========================================
# 1. DEFINE TOOLS
# ==========================================
# Tools are defined through @tool decorator. They enhance the capabilities of the LLM

@tool
def get_weather(location: str) -> str:
    """Gets the current weather for a given location."""
    if "delhi" in location.lower():
        return "The weather in Delhi is currently 32°C and sunny."
    return f"The weather in {location} is currently 22°C and partly cloudy."

@tool
def multiply(a: float, b: float) -> float:
    """Multiplies two numbers together."""
    return a*b

tools = [get_weather, multiply]

# ==========================================
# 2. DEFINE THE STATE
# ==========================================
# State define the schema of the graph.

def AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], operator.add]

# ==========================================
# 3. DEFINE THE NODES
# ==========================================

# Initialise out LLM
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

# Bind the tools with llm
llm_with_tools = llm.bind_tools(tools)

# Define the behaviour of the node
def call_model(state: AgentState):
    messages = state['messages']
    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}

tool_node = ToolNode(tools)

# ==========================================
# 4. DEFINE THE ROUTING LOGIC (The Edges)
# ==========================================

def should_continue(state: AgentState) -> Literal['continue', 'end']:
    """
    Conditional Edge logic.
    Checks the last message from the LLM. If the LLM decided to call a tool,
    we route to the ToolNode ("continue"). If not, we end the graph ("end").
    """
    messages = state['messages']
    last_message = messages[-1]

    # If the last message has the attribute .tool_calls then it was trying to call a tool
    if last_message.tool_calls:
        return "continue"
    return "end"

# ==========================================
# 5. BUILD AND COMPILE THE GRAPH
# ==========================================

def build_graph():
    workflow = StateGraph(AgentState)

    workflow.add_edge(START, "agent")
    workflow.add_node("tools", call_model)
    workflow.add_node("agent", tool_node)
    workflow.add_edge("tools", "agent")
    workflow.add_conditional_edges(
        "agent", 
        should_continue,
        {
            "continue": "tools",
            "end": END
        }
    )

    app = workflow.compile()
    return app

# ==========================================
# 6. RUN THE AGENT
# ==========================================

if __name__ == "__main__":
    app = build_graph()

    user_query = "What is 15 multiplied by 8? After you calculate that, tell me the weather in Delhi."
    print(f"User: {user_query}\n")

    initial_state = {"messages": [HumanMessage(content=user_query)]}

    for event in app.stream(initial_state):
        for key, value in event.items():
            print(f"--- Triggered Node: {key} ---")

            # Print the latest message generated by the node
            latest_message = value["messages"][-1]

            if hasattr(latest_message, 'tool_calls') and latest_message.tool_calls:
                print(f"Action: Calling tools -> {latest_message.tool_calls}")
            elif hasattr(latest_message, 'content') and latest_message.content:
                print(f"Output: {latest_message.content}")
            print("\n")